import json

system = """You are a log analysis expert. Your role is to write complete yet concise descriptions of fields in the OCSF format.

*** OCSF Format Intro ***

The Open Cybersecurity Schema Framework is an open-source project, delivering an extensible framework for developing schemas, along with a vendor-agnostic core security schema. Vendors and other data producers can adopt and extend the schema for their specific domains. Data engineers can map differing schemas to help security teams simplify data ingestion and normalization, so that data scientists and analysts can work with a common language for threat detection and investigation. The goal is to provide an open standard, adopted in any environment, application, or solution, while complementing existing security standards and processes.

*** OCSF Overview ***

The framework is made up of a set of data types, an attribute tree, and the taxonomy. It is not restricted to the cybersecurity domain nor to events, however the initial focus of the framework has been a schema for cybersecurity events. OCSF is agnostic to storage format, data collection and ETL processes. The core schema for cybersecurity events is intended to be agnostic to implementations. The schema framework definition files and the resulting normative schema are written as JSON.

*** Goal ***

Each event in OCSF has its set of top level attributes. Some of these attributes are shared across events, while others are specific to a single event. Our goal is to write a global description of each top level attribute, independent of any particular event.

*** Instructions ***

I will provide you with a field name as well as a list of description of that field in the context of each event it is part of. You must return a single description of the field that is independent of the particular event it is part of.
The rules are the following:
- The description should provide information about the role of the field in the context of a generic event.
- The description should be complete: it should provide all the information needed to understand what the field refers to.
- The description should be sound: it must not mislead into misrepresenting the role of the field.
"""

input_template = """Field: {path}

Descriptions
```
{descriptions}
```

Description: """

description_template = """{description} in event {event_name} ({event_desc})"""

user = """{fs}{input}"""


def gen_fewshot():
    ex_1 = {
        "path": "access_list",
        "descriptions": """The list of requested access rights in event file_hosting (File Hosting Activity events report the actions taken by file management applications, including file sharing servers like Sharepoint and services such as Box, MS OneDrive, Google Drive, or network file share services.)
The list of requested access rights in event entity_management (Entity Management events report activity by a managed client, a micro service, or a user at a management console. The activity can be a create, read, update, and delete operation on a managed entity.)""",
        "description": """The list of requested access rights.""",
    }

    ex_2 = {
        "path": "activity_name",
        "descriptions": """The event activity name, as defined by the activity id, in event base_event (The base event is a generic and concrete event. It also defines a set of attributes available in most event classes. As a generic event that does not belong to any event category, it could be used to log events that are not otherwise defined by the schema.)
The Incident activity name, as defined by the <code>activity_id</code>, in event incident_finding (An Incident Finding reports the creation, update, or closure of security incidents as a result of detections and/or analytics. <br><strong>Note: </strong><code>Incident Finding</code> implicitly includes the <code>incident</code> profile and it should be added to the <code>metadata.profiles[]</code> array.)
The Data Security finding activity name, as defined by the <code>activity id</code> in event data security finding (A Data Security Finding describes detections or alerts generated by various data security products such as Data Loss Prevention (DLP), Data Classification, Secrets Management, Digital Rights Management (DRM), Data Security Posture Management (DSPM) and similar tools. These detections or alerts can be created using fingerprinting, statistical analysis, machine learning or other methodologies. The finding describes the actors and endpoints who accessed or own the sensitive data, as well as the resources which store the sensitive data. Note: if the event producer is a security control, the <code>security_control</code> profile should be applied and its <code>attacks</code> information, if present, should be duplicated into the <code>finding.info</code> code object. <br><strong>Note: </strong>If the Finding is an incident, i.e. requires incident workflow, also apply the <code>incident</code> profile or aggregate this finding into an <code>Incident Findings</code>.""",
        "description": """The log event activity name, as defined by the activity id.""",
    }

    ex_3 = {
        "path": "actor",
        "descriptions": """The actor describes the process that was the source of the inventory activity. In the case of user inventory data that could be a particular process or script that is run to scrape the user data. For example, it could be a powershell process that runs to pull data from the Azure AD graph API. in event user_inventory (User Inventory Info events report user inventory data that is either logged or proactively collected. For example, when collecting user information from Active Directory entries.)
Describes details about the actor implicated in the data security finding. Either an actor that owns a particular digital file or information store, or an actor which accessed classified or sensitive data. in event data_security_finding (A Data Security Finding describes detections or alerts generated by various data security products such as Data Loss Prevention (DLP), Data Classification, Secrets Management, Digital Rights Management (DRM), Data Security Posture Management (DSPM), and similar tools. These detections or alerts can be created using fingerprinting, statistical analysis, machine learning or other methodologies. The finding describes the actors and endpoints who accessed or own the sensitive data, as well as the resources which store the sensitive data. Note: if the event producer is a security control, the <code>security_control</code> profile should be applied and its <code>attacks</code> information, if present, should be duplicated into the <code>finding.info</code> code object. <br><strong>Note: </strong>If the Finding is an incident, i.e. requires incident workflow, also apply the <code>incident</code> profile or aggregate this finding into an <code>Incident Findings</code>.)
The actor object describes details about the actor/role/process that was the source of the activity. Note that this is not the threat actor of a campaign but may be part of the campaign. in event software_info (Software Inventory Info events report device software inventory data that is either logged or proactively collected. For example, collecting device information from a CMDB or running a network sweep of connected devices.)
The actor that performed the activity on the <code>file</code> object in event file_activity (File System Activity events report when a process performs an action on a file or folder.)
The actor process that loaded or unloaded the driver/extension. in event kernel_extension_activity (Kernel Extension events report when a driver/extension is loaded or unloaded into the kernel)
The actor object describes details about the user/role/process that was the source of the activity. Note that this is not the threat actor of a campaign but may be part of a campaign. in event api_activity (API events describe general CRUD (Create, Read, Update, Delete) API activities, e.g. (AWS Cloudtrail))
The actor object describes details about the user/role/process that was the source of the activity. Note that this is not the threat actor of a campaign but may be part of a campaign. in event device_config_state_change (Device Config State Change events report state changes that impact the security of the device.)
The actor that performed the activity on the <code>jobs</code> object. in event scheduled_job_activity (Scheduled Job Activity events report activities related to scheduled jobs or tasks.)
The actor that performed the activity on the target file. in event network_file_activity (Network File Activity events report file activities traversing the network, including file storage services such as Box, MS OneDrive, or Google Drive.)
The actor object describes details about the user/role/process that was the source of the activity. Note that this is not the threat actor of a campaign but may be part of a campaign. in event datastore_activity (Datastore events describe general activities (Read, Update, Query, Delete, etc.) which affect datastores or data within those datastores, e.g. (AWS RDS, AWS S3).)
The actor object describes details about the user/role/process that was the source of the activity. Note that this is not the threat actor of a campaign but may be part of a campaign. in event config_state (Device Config State events report device configuration data, device assessments, and/or CIS Benchmark results.)
The actor object describes details about the user/role/process that was the source of the activity. Note that this is not the threat actor of a campaign but may be part of a campaign. in event inventory_info (Device Inventory Info events report device inventory data that is either logged or proactively collected. For example, when collecting device information from a CMDB or running a network sweep of connected devices.)
The actor that loaded or unloaded the <code>module</code>. in event module_activity (Module Activity events report when a process loads or unloads the <code>module</code>.)
The actor that performed the activity on the target <code>process</code>. For example, the process that started a new process or injected code into another process. in event process_activity (Process Activity events report when a process launches, injects, opens or terminates another process, successful or otherwise.)
The actor that performed the activity. in event event_log_activity (Event Log Activity events report actions pertaining to the system's event logging service(s), such as disabling logging or clearing the log data.)""",
        "description": """The actor that was the source of the activity described in the log event.""",
    }

    ex_4 = {
        "path": "file",
        "descriptions": """The email file attachment in event email_file_activity (Email File Activity events report files within emails.)
The file that is the target of the FTP activity. in event ftp_activity (File Transfer Protocol (FTP) Activity events report file transfers between a server and a client as seen on the network.)
The file that is the target of the activity. in event file_hosting (File Hosting Activity events report the actions taken by file management applications, including file sharing servers like Sharepoint and services such as Box, MS OneDrive, Google Drive, or network file share services.)
The file that is the target of the SSH activity. in event ssh_activity (SSH Activity events report remote client connections to a server using the Secure Shell (SSH) Protocol.)
Describes a file that contains classified or sensitive data, in event data_security_finding (A Data Security Finding describes detections or alerts generated by various data security products such as Data Loss Prevention (DLP), Data Classification, Secrets Management, Digital Rights Management (DRM), Data Security Posture Management (DSPM), and similar tools. These detections or alerts can be created using fingerprinting, statistical analysis, machine learning or other methodologies. The finding describes the actors and endpoints who accessed or own the sensitive data, as well as the resources which store the sensitive data. Note: if the event producer is a security control, the <code>security_control</code> profile should be applied and its <code>attacks</code> information, if present, should be duplicated into the <code>finding.info</code> code object. <br><strong>Note: </strong>If the Finding is an incident, i.e. requires incident workflow, also apply the <code>incident</code> profile or aggregate this finding into an <code>Incident Findings</code>.)
The file that is the target of the query. in event file_query (File Query events report information about files that are present on the system.)
The file that is the target of the activity. in event file_activity (File System Activity events report when a process performs an action on a file or folder.)
The file that pertains to the remediation event. in event file_remediation_activity (File Remediation Activity events report on attempts at remediating files. It follows the MITRE countermeasures defined by the D3FEND <a target='_blank' href='https://d3fend.mitre.org'>Matrix</a>. Sub-techniques will include File, such as File Removal or Restore File.)
The file that is the target of the HTTP activity. in event http_activity (HTTP Activity events report HTTP connection and traffic information.)
The file that is the target of the activity. in event network_file_activity (Network File Activity events report file activities traversing the network, including file storage services such as Box, MS OneDrive, or Google Drive.)
The file that is the target of the RDP activity. in event rdp_activity (Remote Desktop Protocol (RDP) Activity events report remote client connections to a server as seen on the network.)
The file that is the target of the SMB activity. in event smb_activity (Server Message Block (SMB) Protocol Activity events report client/server connections sharing resources within the network.)
The file <p style='display:inline;color:red'>targeted by</p> the activity. Example: <code>/var/log/audit.log</code> in event event_log_activity (Event Log Activity events report actions pertaining to the system's event logging service(s), such as disabling logging or clearing the log data.)""",
        "description": """The file that is the target of the activity described in the log event.""",
    }

    ex_5 = {
        "path": "group",
        "descriptions": """Group that was the target of the event in event group_management (Group Management events report management updates to a group, including updates to membership and permissions.)
The administrative group. in event admin_group_query (Admin Group Query events report information about administrative groups.)
Group that was assigned to the new user session. in event authorize_session (Authorize Session events report privileges or groups assigned to a new user session, usually at logon time.)""",
        "description": """The group that is the target of the activity described in the log event.""",
    }

    ex_6 = {
        "path": "dst_endpoint",
        "descriptions": """The responder (server) receiving the email in event email_activity (Email Activity events report SMTP protocol and email activities including those with embedded URLs and files. See the <code>Email</code> object for details.)
The destination network endpoint for the ADS-B system, if telemetry is being remotely broadcasted. in event airborne_broadcast_activity (Airborne Broadcast Activity events report the activity of any aircraft or unmanned system as reported and tracked by Automatic Dependent Surveillance - Broadcast (ADS-B) receivers. Based on the ADS-B standard described in a target='_blank' href='https://www.ecfr.gov/current/title-14/chapter-I/subchapter-F/part-91#91.225'>Code of Federal Regulations (CFR) Title 14 Chapter I Subchapter F Part 91</a> and on the supplemental Federal Aviation Administration (FAA) supplemental orders and guidance described <a target='_blank' href='https://www.faa.gov/about/office_org/headquarters_offices/avs/offices/afx/afs400/afs410/afs-8'>here</a>.)
The responder (server) in a network connection. in event network (Network Activity events.)
The endpoint that received the activity on the target file. in event file_hosting (File Hosting Activity events report the actions taken by file management applications, including file sharing servers like Sharepoint and services such as Box, MS OneDrive, Google Drive, or network file share services.)
Describes the endpoint where classified or sensitive data is stored in, or was accessed from. in event data_security_finding (A Data Security Finding describes detections or alerts generated by various data security products such as Data Loss Prevention (DLP), Data Classification, Secrets Management, Digital Rights Management (DRM), Data Security Posture Management (DSPM), and similar tools. These detections or alerts can be created using fingerprinting, statistical analysis, machine learning or other methodologies. The finding describes the actors and endpoints who accessed or own the sensitive data, as well as the resources which store the sensitive data. Note: if the event producer is a security control, the <code>security_control</code> profile should be applied and its <code>attacks</code> information, if present, should be duplicated into the <code>finding.info</code> code object. <br><strong>Note: </strong>If the Finding is an incident, i.e. requires incident workflow, also apply the <code>incident</code> profile or aggregate this finding into an <code>Incident Findings</code>.)
The server responding to the tunnel connection. in event tunnel_activity (Tunnel Activity events report secure tunnel establishment (such as VPN), teardowns, renewals, and other network tunnel specific activity.)
The Endpoint for which the user session was targeted. in event authorize_session (Authorize Session events report privileges or groups assigned to a new user session, usually at login time.)
The responder (server) in a network connection. in event dns_activity (DNS Activity events report DNS queries and answers as seen on the network.)
The endpoint to which the authentication was targeted. in event authentication (Authentication events report authentication session activities, including user attempts to log on or log off, regardless of success, as well as other key stages within the authentication process. These events are typically generated by authentication services, such as Kerberos, OIDC, or SAML, and may include information about the user, the authentication method used, and the status of the authentication attempt.)
The responder (server) of the DHCP connection. in event dhcp_activity (DHCP Activity events report MAC to IP assignment via DHCP from a client or server.)
The network destination endpoint. in event api_activity (API events describe general CRUD (Create, Read, Update, Delete) API activities, e.g. (AWS Cloudtrail))
The endpoint that received the activity on the target file. in event network_file_activity (Network File Activity events report file activities traversing the network, including file storage services such as Box, MS OneDrive, or Google Drive.)
Details about the endpoint hosting the datastore application or service. in event datastore_activity (Datastore events describe general activities (Read, Update, Query, Delete, etc.) which affect datastores or data within those datastores, e.g. (AWS RDS, AWS S3).)
Details about server providing the web resources. in event web_resources_activity (Web Resources Activity events describe the actions executed on a set of Web Resources.)
The destination network endpoint of the Unmanned Aerial System (UAS), Counter Unmanned Aerial System (CUAS) platform, or other unmanned systems monitoring and/or sensing infrastructure. in event unmanned_systems (Unmanned Systems events report the activity, existence, and/or state of unmanned systems for tracking, mission planning, and other related activities.)
The targeted endpoint for the event log activity. in event event_log_activity (Event Log Activity events report actions pertaining to the system's event logging service(s), such as disabling logging or clearing the log data.)""",
        "description": """The destination endpoint that is the target of the activity described in the log event.""",
    }

    history = []
    for ex in [ex_1, ex_2, ex_3, ex_4, ex_5, ex_6]:
        history.append(
            {
                "role": "user",
                "content": input_template.format(
                    path=ex["path"],
                    descriptions=ex["descriptions"],
                ),
            }
        )
        history.append({"role": "assistant", "content": ex["description"]})

    return history


def gen_system():
    return system


def gen_prompt(name, descriptions, source_descriptions):
    formatted_descriptions = "\n".join(
        description_template.format(
            description=d, event_name=e, event_desc=source_descriptions[e]
        )
        for e, d in descriptions.items()
    )

    user_input = input_template.format(
        path=name,
        descriptions=formatted_descriptions,
    )
    return user_input, gen_fewshot(), gen_system()
